spring:
  datasource:
    url: jdbc:mysql://160.16.139.184:3306/dev_db
    username: dev
    password: Dev69
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: HTML
  jpa:
    show-sql: true
  messages:
    basename: messages